import { DamagePacket } from "./DamagePacket.mjs";
import { DamageResolution } from "./DamageResolution.mjs";

const APPLICATION_FLAG_SCOPE = "wfrp1ed";
const APPLICATION_FLAG_KEY = "damageApplications";
const WOUNDS_INITIALIZED_FLAG_KEY = "woundsInitialized";
const AUTHORIZED_DAMAGE_APPLICATION_OPTION =
	"wfrp1edAuthorizedDamageApplication";

/**
 * Explicit application boundary for already-resolved WFRP damage.
 *
 * Damage calculation and damage application are intentionally separate. This
 * class mutates remaining Wounds only after a caller explicitly requests the
 * application and the current user has permission over the damage target.
 *
 * The target Actor stores the authoritative application transaction keyed by
 * DamagePacket id. This allows a target owner to apply damage even when they do
 * not own the originating ChatMessage, and prevents normal repeated use of the
 * same damage packet.
 */
export class DamageApplication {
	static VERSION = 3;

	static canApply(actor, user = game.user) {
		if (!actor || !user) {
			return false;
		}

		if (user.isGM) {
			return true;
		}

		return actor.testUserPermission(
			user,
			CONST.DOCUMENT_OWNERSHIP_LEVELS.OWNER,
		);
	}

	static transactionFor(actor, packetOrId) {
		if (!(actor instanceof foundry.documents.Actor)) {
			return null;
		}

		const packetId = packetOrId instanceof DamagePacket
			? packetOrId.id
			: String(packetOrId ?? "").trim();

		if (!packetId) {
			return null;
		}

		const applications = actor.getFlag?.(
			APPLICATION_FLAG_SCOPE,
			APPLICATION_FLAG_KEY,
		);
		const transaction = applications &&
			typeof applications === "object" &&
			!Array.isArray(applications)
				? applications[packetId]
				: null;

		return transaction && typeof transaction === "object"
			? foundry.utils.deepClone(transaction)
			: null;
	}

	static isApplied(actor, packetOrId) {
		return this.transactionFor(actor, packetOrId)?.state === "applied";
	}

	static async apply({
		packet,
		resolution,
		targetActor = null,
		user = game.user,
	} = {}) {
		const normalizedPacket = packet instanceof DamagePacket
			? packet
			: DamagePacket.fromJSON(packet);
		const normalizedResolution = resolution instanceof DamageResolution
			? resolution
			: DamageResolution.fromJSON(resolution);

		validatePair(normalizedPacket, normalizedResolution);

		const actor = targetActor ?? await foundry.utils.fromUuid(
			normalizedPacket.targetActorUuid,
		);

		if (!(actor instanceof foundry.documents.Actor)) {
			throw new Error(
				`Damage target '${normalizedPacket.targetActorUuid}' is not an Actor.`,
			);
		}

		if (actor.uuid !== normalizedPacket.targetActorUuid) {
			throw new Error(
				"The supplied target Actor does not match the DamagePacket target.",
			);
		}

		if (!this.canApply(actor, user)) {
			throw new Error(
				"You do not have permission to apply damage to this Actor.",
			);
		}

		if (this.isApplied(actor, normalizedPacket.id)) {
			throw new Error(
				"This damage packet has already been applied to the target Actor.",
			);
		}

		const woundsBefore = readRemainingWounds(actor);
		const amountApplied = normalizedResolution.finalAmount;
		const woundsAfter = Math.max(0, woundsBefore - amountApplied);
		const criticalValue = Math.max(0, amountApplied - woundsBefore);
		const transaction = {
			version: DamageApplication.VERSION,
			id: foundry.utils.randomID(),
			packetId: normalizedPacket.id,
			targetActorUuid: actor.uuid,
			amountApplied,
			woundsBefore,
			woundsAfter,
			criticalValue,
			criticalMode: normalizedPacket.critical.mode,
			criticalResolution: null,
			userId: user?.id ?? "",
			appliedAt: Date.now(),
			state: "applied",
		};
		const existingApplications = actor.getFlag?.(
			APPLICATION_FLAG_SCOPE,
			APPLICATION_FLAG_KEY,
		);
		const applications = existingApplications &&
			typeof existingApplications === "object" &&
			!Array.isArray(existingApplications)
				? foundry.utils.deepClone(existingApplications)
				: {};

		applications[normalizedPacket.id] = foundry.utils.deepClone(transaction);

		await actor.update(
			{
				"system.status.wounds.value": woundsAfter,
				[`flags.${APPLICATION_FLAG_SCOPE}.${APPLICATION_FLAG_KEY}`]:
					applications,
				[`flags.${APPLICATION_FLAG_SCOPE}.${WOUNDS_INITIALIZED_FLAG_KEY}`]:
					true,
			},
			{
				[AUTHORIZED_DAMAGE_APPLICATION_OPTION]: true,
			},
		);

		return foundry.utils.deepFreeze(transaction);
	}

	/**
	 * Persist the immutable result of resolving a critical generated by one
	 * already-applied damage transaction.
	 *
	 * Critical resolution never changes remaining Wounds. It enriches the
	 * authoritative Actor-side application transaction so chat presentation can
	 * be reconstructed even when the target owner cannot edit the original
	 * ChatMessage.
	 */
	static async recordCriticalResolution({
		actor,
		packetId,
		criticalResolution,
		user = game.user,
	} = {}) {
		if (!(actor instanceof foundry.documents.Actor)) {
			throw new Error("Critical resolution requires a target Actor.");
		}

		if (!this.canApply(actor, user)) {
			throw new Error(
				"You do not have permission to resolve critical damage for this Actor.",
			);
		}

		const id = String(packetId ?? "").trim();
		const existing = this.transactionFor(actor, id);

		if (!existing || existing.state !== "applied") {
			throw new Error(
				"Critical resolution requires an applied damage transaction.",
			);
		}

		if (existing.criticalResolution) {
			return foundry.utils.deepFreeze(existing);
		}

		const normalized = normalizeCriticalResolution(
			criticalResolution,
			existing,
		);
		const applications = readApplicationMap(actor);
		const updated = {
			...existing,
			version: DamageApplication.VERSION,
			criticalResolution: normalized,
		};

		applications[id] = foundry.utils.deepClone(updated);

		await actor.update({
			[`flags.${APPLICATION_FLAG_SCOPE}.${APPLICATION_FLAG_KEY}`]:
				applications,
		});

		return foundry.utils.deepFreeze(
			foundry.utils.deepClone(updated),
		);
	}
}

function validatePair(packet, resolution) {
	if (resolution.packetId !== packet.id) {
		throw new Error(
			"DamageResolution does not belong to the supplied DamagePacket.",
		);
	}

	if (resolution.targetActorUuid !== packet.targetActorUuid) {
		throw new Error(
			"DamageResolution target does not match the DamagePacket target.",
		);
	}

	if (resolution.rawAmount !== packet.rawAmount) {
		throw new Error(
			"DamageResolution raw amount does not match the DamagePacket.",
		);
	}
}

function readRemainingWounds(actor) {
	if (
		actor.getFlag?.(
			APPLICATION_FLAG_SCOPE,
			WOUNDS_INITIALIZED_FLAG_KEY,
		) !== true
	) {
		const maximum = Number(actor.woundsMaximum);

		if (Number.isFinite(maximum) && Number.isInteger(maximum)) {
			return Math.max(0, maximum);
		}
	}

	const value = Number(actor.system?.status?.wounds?.value);

	if (!Number.isFinite(value) || !Number.isInteger(value)) {
		throw new Error(
			`Actor '${actor.name ?? actor.id}' has no valid remaining Wounds value.`,
		);
	}

	return Math.max(0, value);
}

function readApplicationMap(actor) {
	const existing = actor.getFlag?.(
		APPLICATION_FLAG_SCOPE,
		APPLICATION_FLAG_KEY,
	);

	return existing && typeof existing === "object" && !Array.isArray(existing)
		? foundry.utils.deepClone(existing)
		: {};
}

function normalizeCriticalResolution(value, transaction) {
	if (!value || typeof value !== "object" || Array.isArray(value)) {
		throw new Error("Critical resolution must be an object.");
	}

	const criticalValue = Number(value.criticalValue);

	if (
		!Number.isFinite(criticalValue) ||
		!Number.isInteger(criticalValue) ||
		criticalValue !== Number(transaction.criticalValue)
	) {
		throw new Error(
			"Critical resolution value does not match the damage transaction.",
		);
	}

	return foundry.utils.deepClone(value);
}
